### ISSUE TITLE
Defaults for optional parameters

### ISSUE THREAD

**Issue by deepfire** [Gabriel439/Haskell-Optparse-Generic-Library#11]
What is the story for defaulting of optionals?

Maybe some constructors like `First` can be employed for that?

**Comment by Gabriella439** [comment]
Are you referring to the `optional-args` library or something else?

**Comment by deepfire** [comment]
`optparse-generic` provides a way to encode optional arguments by including a field of type `Maybe a` into the record.

What I was referring to is a way to provide a default for this optional value -- in the same data structure.

Of course the defaulting can be done manually, later, e.g. via `fromMaybe` -- however in that case `optparse-generic` would be left without means to document the default value in the help message.

**Comment by Gabriella439** [comment]
I think the cleanest solution in this case would be to default them manually later.  I would like to avoid type-level machinery to do something that is reasonably easy to do at the value level.

Really the best solution would be for Haskell to provide support for records with defaults and then to expose that information via the same generics API.

**Comment by 3noch** [comment]
So is it not possible for `optparse-generic` to automatically fill in and display defaults?

**Comment by Gabriella439** [comment]
It probably is possible in theory but it would require some type-level hacking to get it to derive that information from a datatype definition,

**Comment by adamConnerSax** [comment]
I haven't looked at your way of doing this carefully enough but in the version I've been toying with, it's possible to specify defaults as long as you specify them _all_.  You just do that by giving a specific value of the data type you used to generate the parser.  The given value then fills in all the options but any you specify on the command-line override the ones you specified in the hard-coded value. That should be possible the way you are doing things as well, I think. It's not a general purpose solution but might work fine for some people's needs.

**Comment by Gabriella439** [comment]
So I looked more closely into the idea of specifying the defaults for all fields.  The issue I ran into was how to specify the defaults for fields that were lists.  For example, suppose that you have a field like:

``` haskell
data Example = Example { foo :: [Int] }
```

Normally that would translate to a user interface where the user would supply multiple elements of the list by repeated use of the flag `--foo`:

``` bash
$ ./example --foo 1 --foo 2
```

But suppose that the user wanted to specify a default value for the `foo` field of the `Example` type like `[3,4]`.  How would we translate that default back down to `optparse-applicative`?

Right now the parser for repeated `--foo` flags is created by first defining a parser for a single `--foo` flag and then wrapping that in `many` to permit repetition.  However, that means that we can only define a default value for the parser for a single `--foo` value (i.e. just a single `Int`) and not a default value for the field after we've enabled repetition using `many`.

Also, it's not clear what a default value would mean for a repeated field.  For example, suppose that we did figure out how to specify a default value of `[3, 4]` for a repeated `Int` field.  If we supply that default when there are no `--foo` flags on the command line then the user has no way to override the default with the empty list.

**Comment by echatav** [comment]
You could use the same trick as for help messages with `Default` taking the role of `KnownSymbol`. Make a `newtype DefaultValue a = DefaultValue { getField :: a }`. Propagate the default through the class methods using an extra `Maybe a` input and a `maybe mempty Options.value` modifier. Then define instances for

``` haskell
instance (ParseField a, Default (DefaultValue a)) => ParseField (DefaultValue a) where
    parseField _ h m = DefaultValue <$> parseField (getField def) h m
instance (ParseFields a, Default (DefaultValue a)) => ParseFields (DefaultValue a)
instance (ParseRecord a, Default (DefaultValue a)) => ParseRecrod (DefaultValue a)
```

edit: Actually, I think this will not work well for lists, `First` or `Last`. I'd recommend users just use `Maybe` fields and use `fromMaybe` in their execution code to get a default value. This is what I'm doing in my own `optparse-applicative` code anyway because I have to resolve values from the command line, a config file and defaults anyway.

**Comment by Gabriella439** [comment]
That still doesn't solve the issue of how to interpret a default value for a field that is a list

**Comment by echatav** [comment]
Arguably, lists (except for strings) should not be able to have defaults which only really make sense for a (missing) single entry field. You should give them and `Any`, `Sum`, etc a default of `mempty` so that trying to define a default gives an overlapping instance type error. A bigger problem is that you can't (without some ugly/confusing hacks) do different defaults for the same type found in a given record which is a very common use case. This would all be easier if we had dependent types ^_^

**Comment by PierreR** [comment]
What I would find very convenient is the ability to specify defaults using an external file (ala `configurator`). I actually need something a bit more complex as I have to read defaults from different file according to user input. I currently handle this with a `make` file but it seems a bit overkilled. So for instance `make foo ZONE=test` would read default configuration from a file called ".env-test" ...

I don't see how to do this in an "extra" library on top of `optparse-generic` and `configurator` because ideally the parser should check that every field is present (even if only some of them are provided by the command line and the others from the file).

In case it is not obvious arguments provided on the command line override the one from the file.

**Comment by echatav** [comment]
As I understand it, a full configuration system with configuration files or environment variables is outside of the scope of `optparse-generic` which is intended only for simple command line parsing. I would do something like this to resolve a configuration between the command line and a configuration file:

> example.hs

``` haskell
{-# LANGUAGE DeriveGeneric #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards #-}

module Main where

import Data.Aeson
import Data.Aeson.Types
import Data.Foldable
import Data.Maybe
import Data.Yaml
import GHC.Generics
import Options.Generic

data PartialCommand = PartialCommand
  { foo :: Maybe Int
  , bar :: Maybe Double
  } deriving (Generic)
instance ParseRecord PartialCommand

data Command = Command
  { cfoo :: Int
  , cbar :: Double
  } deriving (Generic,Show)
instance FromJSON Command where
  parseJSON = genericParseJSON defaultOptions{fieldLabelModifier = tail}

resolveCommand :: Command -> PartialCommand -> Command
resolveCommand Command{..} PartialCommand{..} =
  Command (fromMaybe cfoo foo) (fromMaybe cbar bar)

main = do
  defMaybe <- decodeFile "default.yaml"
  for_ defMaybe $ \def -> do
    command <- resolveCommand def <$> getRecord "command line parser"
    print (command :: Command)
```

> default.yaml

``` yaml
foo: 0
bar: 0
```

``` bash
> stack runghc example.hs -- --foo 2
Command {cfoo = 2, cbar = 0.0}
```

**Comment by PierreR** [comment]
@echatav Thanks. Exactly what I was searching for. Do you know if there is a way to merge the two records in `resolveCommand` in an automate way (in case there are say more than 10 fields) ? 

I do see it is orthogonal concern. Sorry for the distraction.

**Comment by Gabriella439** [comment]
If you make the record fields `Monoid`s then you can derive a `Monoid` instance for the entire record using the `generic-deriving` package: https://hackage.haskell.org/package/generic-deriving-1.10.4/docs/Generics-Deriving-Monoid.html

**Comment by echatav** [comment]
@PierreR I can't think of a nice way to automate that boilerplate :-/

**Comment by Profpatsch** [comment]
There is actually a very nice way: A combination of [`LambdaCase`](https://prime.haskell.org/wiki/LambdaCase), [`ViewPatterns`](https://ocharles.org.uk/blog/posts/2014-12-02-view-patterns.html) and [`Data.Coerce`](https://hackage.haskell.org/package/base-4.8.0.0/docs/Data-Coerce.html):

``` haskell
data Args
   = Args { projectdir :: Maybe FilePath O.<?>"directory that the command is executed in"
          , watch      :: FilePath       O.<?> "file/directory to be watched"
          , command    :: Text           O.<?> "command to build executable"
          , exe        :: FilePath       O.<?> "executable to run after rebuild" }
   deriving (Generic)
instance O.ParseRecord Args


main :: IO ()
main = do
  O.getRecord "rebuild a long-running program on source change" >>= \case
    Args { projectdir = fromMaybe "." . O.unHelpful -> pd
         , watch      = coerce -> w
         , command    = O.Helpful cmd
         , exe        = O.Helpful e }
      -> watcher cmd pd w e
```

You can decide whether you want to do `coerce` or explicitly use `Helpful` and `unHelpful`. `coerce` should be able to unwrap multiple layers of newtypes.

Maybe this should be a part of the tutorial?

**Comment by Gabriella439** [comment]
That's a nice idea!  Would you like to contribute this to the tutorial?  If not, I can write this up

**Comment by Profpatsch** [comment]
I’m a little full the next days, but I can write it into my todo list once I find the time.

**Comment by mikeplus64** [comment]
Could use `[Symbol]` for default values to simply be the default command-line arguments, verbatim. The display of default values in help can just be `unwords . (reifystuff :: Proxy [Symbol] -> Text)`, i.e., exactly as a user would use it.

**Comment by Profpatsch** [comment]
Apparently there’s now a bit more type-trickery possible with a type-family called `:::`. From the documentation:

```haskell
data Example w = Example
    { foo :: w ::: Int    <?> "Documentation for the foo flag"
    , bar :: w ::: Double <?> "Documentation for the bar flag"
    } deriving (Generic)

instance ParseRecord (Example Wrapped)
deriving instance Show (Example Unwrapped)
```

So parameterizing on some type implementing `:::` (there’s exactly two: `Wrapped` and `Unwrapped`) gives you the ability to get both representations, using `unwrapRecord` (why not keep naming symmetry and call it `parseUnwrappedRecord`?) to extract to the unwrapped version.

What to use depends on personal taste, I guess. The manual version with `ViewPatterns` is a tiny bit more verbose, but provides greater flexibility and probably less mental overhead.

**Comment by Gabriella439** [comment]
@mikeplus64: That's pretty clever.  I like that idea.  I probably don't have time to implement it myself but I'd accept a pull request to add this

**Comment by gbaz** [comment]
note: I understand the "list" objection but also it is worth noticing that there _is_ a default value combinator directly in optparse-applicative: https://hackage.haskell.org/package/optparse-applicative-0.14.2.0/docs/Options-Applicative.html#v:value

So it seems to me that it is unfortunate that optparse-generic has a portion of the optparse-applicative featureset it just can't provide an interface to here...

**Comment by ghorn** [comment]
Just wanted to say that I think this is an important issue. This library is so much more convenient than directly using optparse-applicative. I always try to use optparse-generic for new applications but this issue usually blocks me. Just one data point *shrug*

**Comment by Gabriella439** [comment]
Alright, if somebody submits a pull request implementing this functionality then I'll accept it

**Comment by Naveenaidu** [comment]
I've trying to import the type operator `<!>` , but ghci always complains saying:

```
Module ‘Options.Generic’ does not export ‘type (<!>)’
    |
202 | import           Options.Generic                  (type (<!>))
```

I imported the module using:
```
import           Options.Generic                  (type (<!>))
```

What might I be doing wrong?
