### ISSUE TITLE
system-filepath dependency

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Optparse-Generic-Library#15]
Just to voice the fact that I don't like the dependency on `system-filepath` which is known to be deprecated for quite a while now. Somehow it gives the wrong signal.

That said, I don't mind much. So please do close the issue if you feel this dependency has its merit ;-)

**Comment by Gabriella439** [comment]
All the alternative `FilePath` implementations (except the `path` library) are not abstract types, so I still prefer to provide support for `system-filepath`.  I also plan to have `turtle` re-export this functionality, so `system-filepath` support is necessary for `turtle`.

**Comment by PierreR** [comment]
Sure, it is just a shame the Haskell community doesn't converge for such a common library ... I guess you are waiting for `ghc` to abstract `FilePath` before moving on to another implementation.

**Comment by Gabriella439** [comment]
Yeah, I'm waiting for an abstract `FilePath` type before migrating

**Comment by cblp** [comment]
Why not use `path` package?

**Comment by Gabriella439** [comment]
The main reason I added `system-filepath` is mainly because (A) `turtle` also uses `system-filepath` and (B) `system-filepath` is a really cheap dependency to add

**Comment by georgefst** [comment]
Should this really be closed? I appreciate it's low priority but `system-filepath` isn't coming back.

I've dropped `optparse-generic` from a project because `system-filepath` has a custom setup script, which is a pain for cross-compilation (although, it looks like a pretty trivial one, so one could probably fork and just remove it).

**Comment by Gabriella439** [comment]
Alright, I would accept a pull request to remove the dependency on `system-filepath`

**Comment by georgefst** [comment]
> The main reason I added `system-filepath` is mainly because (A) `turtle` also uses `system-filepath` and (B) `system-filepath` is a really cheap dependency to add

Just noting here that (A) may not hold forever, after your comment at https://github.com/Gabriel439/Haskell-Turtle-Library/issues/54#issuecomment-919695701.
