### ISSUE TITLE
Provide options for `genericParseRecord`

### ISSUE THREAD

**Issue by echatav** [Gabriel439/Haskell-Optparse-Generic-Library#16]
In `aeson` the generic parser class looks like

``` haskell
class GFromJSON f where
  gParseJSON :: Options -> Value -> Parser (f a)
```

where the `Options` type allows you to, among other things, provide a field name modifier and a constructor name modifier. Both of these at least would be useful to provide for the `genericParseRecord` function.

**Comment by Gabriella439** [comment]
Yeah, it would be useful to provide functionality like dropping the field prefix similar to `aeson`.  This seems like a reasonable request to me
