### ISSUE TITLE
Provide a wrapper for Prelude FilePath

### ISSUE THREAD

**Issue by Profpatsch** [Gabriel439/Haskell-Optparse-Generic-Library#27]
`system-filepath` [has been deprecated](https://hackage.haskell.org/package/system-filepath-0.4.13.4) for quite some time now, but when I use `arg :: FilePath` with the `Prelude` `FilePath`, the help message I get is `--arg STRING`.

It would be nice to have a newtype wrapper for `FilePath` that changes the type in the message.

**Comment by Gabriella439** [comment]
Just to clarify, you get `--arg STRING` because you are using `Prelude.FilePath`, correct?

I believe the correct solution here is for somebody to complete the [Abstract `FilePath` proposal](https://ghc.haskell.org/trac/ghc/wiki/Proposal/AbstractFilePath)

**Comment by Profpatsch** [comment]
> Just to clarify, you get --arg STRING because you are using Prelude.FilePath, correct?

Yes

> I believe the correct solution here is for somebody to complete the Abstract FilePath proposal

Since that’s 17 months old and there’s nobody working on it (and when it’s done it will still take 2 releases to be implemented), maybe a special newtype might be a good idea in the meantime?

**Comment by Gabriella439** [comment]
I still think `system-filepath` is fine to use even if it is deprecated.  The library still works

My main concern is that I don't feel that `optparse-generic` is the appropriate home for a `newtype` around `FilePath`.  That really belongs in `base`

**Comment by Profpatsch** [comment]
Hm, okay.
