### ISSUE TITLE
Lists of arguments are not shown to the user very well

### ISSUE THREAD

**Issue by Profpatsch** [Gabriel439/Haskell-Optparse-Generic-Library#29]
When I have something like that:

```haskell
data Args
   = Args {
            projectdir :: Maybe FilePath O.<?> "directory that the command is executed in"
          , watch      :: [FilePath]     O.<?> "files/directories to be watched" }
   deriving (Generic)
```

the help text is as follows:

```
Usage: watch-server [--projectdir STRING] [--watch STRING]
Available options:
  -h,--help                Show this help text
  --projectdir STRING      directory that the command is executed in
  --watch STRING           files/directories to be watched
```

`Maybe a` produces the same string as `[a]`, the user doesn’t see that the argument can be given multiple times.

The other way around:

```haskell
data Args = Args
    { foo :: FilePath } deriving Generic
```

```
$ cabal run -- --foo ./a --foo ./b
Invalid option `--foo`
```

The message should probably be `Only one '--foo' argument allowed`.

**Comment by Gabriella439** [comment]
I think this fix should be pushed upstream into `optparse-applicative`.  `optparse-generic` just does the obvious thing and uses `many` for `[]` and `optional` for `Maybe`.  The fix would be to override `many` in the `Alternative` instance for `Parser` to improve the error message and help text

**Comment by Gabriella439** [comment]
I saw the discussion in the other issue and learned that I could use the `prefMultiSuffix` option to set this behavior.  Now this will display a trailing `...` when parsing a list of options

**Comment by Profpatsch** [comment]
yay
