### ISSUE TITLE
Defining short options?

### ISSUE THREAD

**Issue by JamesMcMahon** [Gabriel439/Haskell-Optparse-Generic-Library#33]
I didn't see it in the documentation or I just missed it.

Is there a way to define a short option,

for instance, for `--foo` is there a way to define a short hand option, ie, `-f`?

**Comment by Gabriella439** [comment]
No, this doesn't provide support for short options.  However, now that there is a way to customize generated options using a `Modifiers` record I could add support for that

**Comment by JamesMcMahon** [comment]
That would be great.

Is there documentation for `Modifiers` outside of function reference at https://hackage.haskell.org/package/optparse-generic-1.1.5/docs/Options-Generic.html?

**Comment by Gabriella439** [comment]
I opened up a pull request at #36 implementing support for short options and also improving the documentation.  Check that out and see if that satisfies your needs

**Comment by JamesMcMahon** [comment]
Thanks! I'll close this up and continue the discussion in the pull request.
