### ISSUE TITLE
A way to display the help message

### ISSUE THREAD

**Issue by ryantm** [Gabriel439/Haskell-Optparse-Generic-Library#34]
Hello,

I have two options that are lists of integers. I'd like to show the help message if both lists are empty.

I don't think you can express that requirement in optparse-generic (please correct me if I'm wrong!), so it would be nice to be able to get the help message or cause the help message to be printed out in cases where the data structure cannot encode certain option requirements. I don't think this would exactly work, but something like this that instead gets the option data type in there:

```haskell
main = do
  opts <- unwrapRecord "unwrap-example"
  if (doesntMatchRequirements opts)
  then printHelp "unwrap-example"
  else print (opts :: Options Unwrapped)
```

Ryan

**Comment by Gabriella439** [comment]
I could add a variation on `getRecord`/`unwrapRecord` called `getWithHelp`/`unwrapWithHelp` that returns the command to print the help output.  Then you could do:

```haskell
main = do
    (opts, printHelp) <- unwrapWithHelp "unwrap-example"
    if doesn'tMatchRequirements opts  -- Note: Apostrophes in the middle of names are legal
        then printHelp
        else print (opts :: Options Unwrapped)
```

How does that sound?

**Comment by ryantm** [comment]
Sounds great!
