### ISSUE TITLE
How do I use modifiers with wrapped records?

### ISSUE THREAD

**Issue by jchia** [Gabriel439/Haskell-Optparse-Generic-Library#45]
I need argument `--foo-bar` mapped to field `fooBar`. I also need the field to have help.

`parseRecordWithModifiers lispCaseModifiers` allows the mapping from `--foo-bar` to `fooBar`. `unwrapRecord` allows adding help to fields using `<?>`. But there is no `unwrapRecordWithModifiers`. How do I use a modifier, attach help description to fields and still get record fields that are not wrapped in `Helpful`?

**Comment by jchia** [comment]
Please ignore. I just had to define the ParseRecord instance with `parseRecordWithModifiers lispCaseModifiers` instead of just deriving it.

**Comment by Gabriella439** [comment]
No problem :)
