### ISSUE TITLE
Using a record as command options

### ISSUE THREAD

**Issue by ghallak** [Gabriel439/Haskell-Optparse-Generic-Library#52]
I have different commands and each of them accepts different options. So I'm using a separate record to represent each command's options, but I couldn't get that to work.

Here's an example, I have the file `args.hs`:

```haskell
{-# LANGUAGE DeriveGeneric       #-}
{-# LANGUAGE OverloadedStrings   #-}
{-# LANGUAGE ScopedTypeVariables #-}

import Options.Generic

data FirstCommandOpts = FirstCommandOpts
  { xs :: Maybe Int
  , ys :: Maybe Bool
  } deriving (Generic, Read, Show)

data Cmd
  = FirstCommand FirstCommandOpts
  | SecondCommand
  deriving (Generic, Read, Show)

instance ParseRecord Cmd
instance ParseFields Cmd
instance ParseField  Cmd
instance ParseRecord FirstCommandOpts
instance ParseFields FirstCommandOpts
instance ParseField  FirstCommandOpts

main :: IO ()
main = do
  (cmd :: Cmd) <- getRecord "Example"
  case cmd of
    FirstCommand opts -> putStrLn "First Commmand"
    SecondCommand     -> putStrLn "Second Command"
```

When I run it, I get the following:
```
$ ./args.hs secondcommand
Second Command

$ ./args.hs firstcommand
Missing: FIRSTCOMMANDOPTS

Usage: args.hs firstcommand FIRSTCOMMANDOPTS

$ ./args.hs firstcommand --xs 2

Invalid option `--xs'

Usage: args.hs firstcommand FIRSTCOMMANDOPTS
```

My question is, how to get `./args.hs firstcommand` and `./args.hs firstcommand --xs 2` to work, and if there's no way to get this to work, shouldn't I get a compilation error instead of a message about wrong usage?

**Comment by Gabriella439** [comment]
The reason there is no type error is because there the default implementation of `ParseField` that uses the `Read` instance for a type.  I believe your example would work if you did:

```
./args.hs firstcommand 'FirstCommandOpts { xs = Nothing, ys = Nothing }'
```

Of course, that's probably not what you want.  In general, `optparse-generic` only supports options one level deep, so you would need to restructure your original type that you parse into as:

```haskell
data Cmd
  = FirstCommand { xs :: Maybe Int, ys :: Maybe Bool }
  | SecondCommand
  deriving (Generic, Read, Show)
```

**Comment by ghallak** [comment]
I need to have `FirstCommandOpts` as a separate record, so I'll go with `optparse-applicative` to do that.

Thank you for your answer.

**Comment by Gabriella439** [comment]
You're welcome! 🙂
