### ISSUE TITLE
Giant (~5GB) Args.dump-hi file with ghc 8.2.2 and -O2

### ISSUE THREAD

**Issue by ThomasLocke** [Gabriel439/Haskell-Optparse-Generic-Library#53]
When compiling the following with ghc 8.2.2 and -O2 it takes forever and it leaves me with a gigantic (about 5GB) Args.dump-hi file

```haskell
data Options w = Options
  { database :: w ::: Maybe String  <?> "PostgreSQL database name"
  , host     :: w ::: Maybe String  <?> "PostgreSQL host"
  , httpPort :: w ::: Maybe Int     <?> "Web server port"
  , port     :: w ::: Maybe Integer <?> "PostgreSQL port"
  , secret   :: w ::: Maybe String  <?> "PostgreSQL password"
  , user     :: w ::: Maybe String  <?> "PostgreSQL user"
  } deriving (Generic)

instance ParseRecord (Options Wrapped)
deriving instance Show (Options Unwrapped)
```

When compiling with -O0 it works as intended. No large files and compiling is fast.

Switching to ghc 8.0.2 fixes the issue. Here both -O0 and -O2 works without a hitch. Fast compiling and no large build artifacts.

I suspect this is actually a bug in 8.2.2. Sadly I'm forced to use 8.2.2. I would really like to continue using Optparse-Generic. Anybody aware of any clever workarounds that might mitigate this issue?

**Comment by Gabriella439** [comment]
This looks very similar to https://github.com/Gabriel439/Haskell-Optparse-Generic-Library/issues/47

**Comment by ThomasLocke** [comment]
@Gabriel439 you're right, it does. Except #47 experience the problem with 8.0.2 where I have it with 8.2.2 and not 8.0.2, the latter actually fixing it for me.

This is very odd, and quite unfortunate. I was really enjoying Optparse-Generic, but I guess it's back to parseargs until we move away from 8.2.2.

**Comment by Gabriella439** [comment]
Yeah, the best guess I have is that it is a GHC compiler bug since it works for different versions of the compiler and different optimization flags

**Comment by ThomasLocke** [comment]
@Gabriel439 interestingly the problem goes away if I change the code to this:

```haskell
data Options = Options
  { database :: Maybe String  <?> "PostgreSQL database name"
  , host     :: Maybe String  <?> "PostgreSQL host"
  , httpPort :: Maybe Int     <?> "Web server port"
  , port     :: Maybe Integer <?> "PostgreSQL port"
  , secret   :: Maybe String  <?> "PostgreSQL password"
  , user     :: Maybe String  <?> "PostgreSQL user"
  } deriving (Generic, Show)

instance ParseRecord Options
```

So it seems to be related to the whole Wrapped/UnWrapped thing.

**Comment by ThomasLocke** [comment]
I can live with manually having to unbox the individual options, but it eludes me how to do that. How do I actually get to the user `Maybe String` after having called `getRecord`? The type has a weird shape that is definitely a cut above my pay grade!  :smiley:

**Comment by Gabriella439** [comment]
@ThomasLocke: If you got rid of the `Wrapped`/`Unwrapped` stuff then you no longer need the `<?>` operators any longer.  You can turn them into comments:

```haskell
data Options = Options
  { database :: Maybe String  -- ^ "PostgreSQL database name"
  , host     :: Maybe String  -- ^ "PostgreSQL host"
  , httpPort :: Maybe Int     -- ^ "Web server port"
  , port     :: Maybe Integer -- ^ "PostgreSQL port"
  , secret   :: Maybe String  -- ^ "PostgreSQL password"
  , user     :: Maybe String  -- ^ "PostgreSQL user"
  } deriving (Generic, Show)
```

**Comment by ThomasLocke** [comment]
@Gabriel439 but then I lose my fancy-pancy help output - or rather, it's still there, it's just a whole lot less fancy-pancy.

Or am I missing something?

**Comment by Gabriella439** [comment]
@ThomasLocke: Sorry, my mistake.  You're right.

So if you keep the `(<?>)` operators and don't use `Wrapped`/`Unwrapped` then you need to unwrap each field using the `unHelpful` function:

```haskell
unHelpful :: a <?> s -> a
```

**Comment by ThomasLocke** [comment]
The amount of awesome here is, well, awesome.

This just works. Thank you so very much for the help @Gabriel439

**Comment by Gabriella439** [comment]
You're welcome! :slightly_smiling_face:
