### ISSUE TITLE
Haddock failure

### ISSUE THREAD

**Issue by georgefst** [Gabriel439/Haskell-Optparse-Generic-Library#66]
322d651 seems not to be reflected [in the tarball](https://hackage.haskell.org/package/optparse-generic-1.4.0/src/src/Options/Generic.hs) on Hackage. My guess would be that you uploaded fresh docs only.

Unfortunately, this means that when Cabal is configured to build documentation for all dependencies, it fails on `optparse-generic`. I know it's kind of annoying, but would a `1.4.0.1` release with the fix be possible?

**Comment by Gabriella439** [comment]
Fixed by `optparse-generic-1.4.1`

**Comment by georgefst** [comment]
Thanks!

**Comment by Gabriella439** [comment]
@georgefst: You're welcome! 🙂
