### ISSUE TITLE
Export unwrap?

### ISSUE THREAD

**Issue by dacto** [Gabriel439/Haskell-Optparse-Generic-Library#69]
Would it be possible to export `unwrap`? I'd like to use it with `getRecordWith`.

https://github.com/Gabriel439/Haskell-Optparse-Generic-Library/blob/579274bc03b250668c3918270517f5b08a25f9db/src/Options/Generic.hs#L1214-L1215

ie: 
```haskell
main :: IO ()
main = do
    Options {..} <- unwrap <$> (getRecordWith infoMods prefMods)
    ...
```

**Comment by dacto** [comment]
Thank you! 👍

**Comment by Gabriella439** [comment]
@dacto: You're welcome!  I will schedule a new release to Hackage in about a month, if that's okay with you, since I just released a few days ago (mainly to avoid version churn)

**Comment by dacto** [comment]
@Gabriel439 of course, sounds good.
