### ISSUE TITLE
ParseFields ByteString?

### ISSUE THREAD

**Issue by PierreR** [Gabriel439/Haskell-Optparse-Generic-Library#7]
I have just given it another try but I am now blocked by the fact there isn't any `ParseFields` instance for ByteString.

Here is my command line options:

```
data CmdOptions = CmdOptions
  { vCloudURL  :: String
  , vCloudUser :: ByteString
  , vCloudPass :: ByteString
  , vAppId     :: String
  , vmName     :: Text
  , vmAction   :: String
  } deriving (Show, Generic)
```

Does it make sense to add one ? (I am just following `wreq` expectation)

Cheers,

**Comment by Gabriella439** [comment]
Pull request #8 is in progress which will fix this issue

**Comment by PierreR** [comment]
Thanks. As a note,I have using the fix from the PR branch for a while now and it has been working nicely.
