### ISSUE TITLE
Redundant help message for NonEmptyList field

### ISSUE THREAD

**Issue by hw202207** [Gabriel439/Haskell-Optparse-Generic-Library#97]
Given data type like
```haskell
data Options w = Options
  { filepath :: w ::: NonEmpty String <?> "xxxxx.",
  }
  deriving (Generic)
```

The help message is generated like this:

```
Usage: mwb-erd --filepath STRING [--filepath STRING]

Available options:
  -h,--help                Show this help text
  --filepath STRING        xxxx.
  --filepath STRING        xxxx.
```

I'm wondering it is because how we implemented the `ParseFields` for `NonEmptyList`

```haskell
instance ParseField a => ParseFields (NonEmpty a) where
    parseFields h m c d = (:|) <$> parseField h m c d <*> parseListOfField h m c d
```

The `optparse-applicative` added a special `some1` for `NonEmptyList`
https://github.com/pcapriotti/optparse-applicative/pull/382/files

I tried to change the `ParseFields` implementation and works well (one help message).
(what I did actually is create a `newtype` wraps `NonEmpty` and implement `ParseFields` type class.)

```haskell
import import Options.Applicative.NonEmpty (some1)

instance ParseField a => ParseFields (NonEmpty a) where
    parseFields h m c d =  some1 (parseField h m c d)
```

Does it sound reasonable to change the library?

**Comment by hw202207** [comment]
Thank you!!

**Comment by Gabriella439** [comment]
You're welcome! 🙂
